1. Create a sample code of partitioning. Use 5 as k argumemnt.

In [1]:
import numpy as np

def partition_list(input_list, k):
    """
    Partitioning a list such a way that k smallest elements are in the first k positions and remining elements 
    after k positions.

    Parameters:
    - input_list: The list to be partitioned.
    - k: The number of positions.

    Returns:
    A list with k smallest elements in the beginning of the list.
    """
    return np.partition(input_list,k)

# Example usage:
input_list = [911,45,54,21,29,43,143,69,3,1,53,84,75]
k = 5

result = partition_list(input_list, k)
print(result)


[  1   3  29  21  43  45  53  69  75  54  84 143 911]


2. Create a sample structure array using following specification:
- name: OrderDate, format: unicode maximum 8 characters
- name: OrderAmount, format: float 8-bytes
- name: OrderNumber, format: integer 4-bytes
- name: OrderName, format: unicode maximum 20 characters

In [2]:
# Defining the data types for each field in the structured array
data=np.zeros(10,dtype={'names':('OrderDate','OrderAmount','OrderNumber','OrderName'),
                       'formats':('U8','f8','i4','U20')})
print(data.dtype)

[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')]


3. Using #2, create a NumPy array of 10 elements with proper initialization of the structured array. Note order numbers must be between 101 - 110.

In [3]:
# generating order dates in the month of november 2023
OrderDate=[f'110{i + 1}2023' for i in range(10)]
print(OrderDate)           

['11012023', '11022023', '11032023', '11042023', '11052023', '11062023', '11072023', '11082023', '11092023', '110102023']


In [4]:
# generating Order amounts for each order
OrderAmount = [45.0 * np.random.randint(1,100) for _ in range(10)] 
OrderAmount

[4455.0, 225.0, 1980.0, 2835.0, 1215.0, 720.0, 1350.0, 1800.0, 405.0, 4455.0]

In [5]:
# assigning Order Number for each order
OrderNumber = [_ for _ in range(101,111)]
np.random.shuffle(OrderNumber)
OrderNumber

[102, 103, 101, 104, 109, 106, 110, 105, 107, 108]

In [6]:
# generating OrderName for each order
OrderName = [f'Order{OrderNumber[i]}' for i in range(10)]
print(OrderName)

['Order102', 'Order103', 'Order101', 'Order104', 'Order109', 'Order106', 'Order110', 'Order105', 'Order107', 'Order108']


In [7]:
# asigning the data to structured array generated in Ques #2
data['OrderDate']=OrderDate
data['OrderAmount']=OrderAmount
data['OrderNumber']=OrderNumber
data['OrderName']=OrderName
print(data)

[('11012023', 4455., 102, 'Order102') ('11022023',  225., 103, 'Order103')
 ('11032023', 1980., 101, 'Order101') ('11042023', 2835., 104, 'Order104')
 ('11052023', 1215., 109, 'Order109') ('11062023',  720., 106, 'Order106')
 ('11072023', 1350., 110, 'Order110') ('11082023', 1800., 105, 'Order105')
 ('11092023',  405., 107, 'Order107') ('11010202', 4455., 108, 'Order108')]


4. Using the array in #3, filter the array to return orders with order number less than 105. 

In [8]:
# Filtering out orders where ordernumber is less than 105 and printing them
print(data[data['OrderNumber']<105])

[('11012023', 4455., 102, 'Order102') ('11022023',  225., 103, 'Order103')
 ('11032023', 1980., 101, 'Order101') ('11042023', 2835., 104, 'Order104')]


5. Using the code snippet below, fill-in the cell to generate the array as shown at the bottom. 
- You will need to use fancy indexing and masking. 
- Select rows with indices 0, 3, 4, 6, 7
- Use column masking to return every other columns. The first column will be returned, 2nd column will not and so on. 

In [9]:
import numpy as np

rng = np.random.RandomState(0)
x = rng.randint(10, size=(10, 10))

In [10]:
x

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [11]:
rows = np.array([0, 3, 4, 6, 7]) # selecting the rows 0,3,4,6,7 only
cols = np.arange(0, 10, 2) #selecting every alternate column

result = x[rows][:, cols]

print(result)

[[5 3 7 3 2]
 [2 8 3 3 0]
 [9 0 7 2 2]
 [8 1 9 3 7]
 [0 5 4 6 4]]
